package course.ch26;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Shared H2 in-memory database setup for chapter 26 tests.
 */
public final class JdbcTestSupport {

    private JdbcTestSupport() {
    }

    /**
     * Creates a connection to a fresh in-memory H2 database.
     *
     * @return a new JDBC connection
     * @throws SQLException if a database error occurs
     */
    public static Connection newConnection() throws SQLException {
        String url = "jdbc:h2:mem:ch26-" + System.nanoTime() + ";DB_CLOSE_DELAY=-1";
        return DriverManager.getConnection(url, "sa", "");
    }

    /**
     * Creates the users table used by prepared-statement examples.
     *
     * @param connection the database connection
     * @throws SQLException if a database error occurs
     */
    public static void createUsersTable(Connection connection) throws SQLException {
        try (Statement stmt = connection.createStatement()) {
            stmt.execute("""
                    CREATE TABLE IF NOT EXISTS users (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(100) NOT NULL,
                        email VARCHAR(200) NOT NULL
                    )""");
        }
    }

    /**
     * Creates the accounts table used by transaction examples.
     *
     * @param connection the database connection
     * @throws SQLException if a database error occurs
     */
    public static void createAccountsTable(Connection connection) throws SQLException {
        try (Statement stmt = connection.createStatement()) {
            stmt.execute("""
                    CREATE TABLE IF NOT EXISTS accounts (
                        id INT PRIMARY KEY,
                        balance DOUBLE NOT NULL
                    )""");
            stmt.execute("DELETE FROM accounts");
            stmt.execute("INSERT INTO accounts (id, balance) VALUES (1, 1000.00)");
            stmt.execute("INSERT INTO accounts (id, balance) VALUES (2, 500.00)");
        }
    }

    /**
     * Creates the students table used by exercise tests.
     *
     * @param connection the database connection
     * @throws SQLException if a database error occurs
     */
    public static void createStudentsTable(Connection connection) throws SQLException {
        try (Statement stmt = connection.createStatement()) {
            stmt.execute("""
                    CREATE TABLE IF NOT EXISTS students (
                        id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name VARCHAR(100) NOT NULL,
                        email VARCHAR(200) NOT NULL
                    )""");
            stmt.execute("DELETE FROM students");
            stmt.execute("INSERT INTO students (name, email) VALUES ('Alice', 'alice@school.edu')");
            stmt.execute("INSERT INTO students (name, email) VALUES ('Bob', 'bob@school.edu')");
        }
    }
}
