package course.ch20.examples;

import java.util.List;

/**
 * Demonstrates Maven lifecycle phases conceptually.
 *
 * <p>This class models the Maven build lifecycle as data. In a real Maven
 * build, these phases are executed sequentially by the build tool. Here
 * we represent them programmatically to support learning and testing.
 */
public class MavenLifecycleDemo {

    /**
     * Represents a single Maven lifecycle phase.
     *
     * @param name        the phase name (e.g., "compile")
     * @param description what happens during this phase
     */
    public record Phase(String name, String description) {}

    /**
     * The default Maven build lifecycle phases in execution order.
     */
    public static final List<Phase> DEFAULT_LIFECYCLE = List.of(
            new Phase("validate", "Validate the project is correct and all necessary information is available"),
            new Phase("compile", "Compile the source code of the project"),
            new Phase("test", "Run unit tests using a suitable testing framework"),
            new Phase("package", "Package compiled code into a distributable format (e.g., JAR)"),
            new Phase("verify", "Run integration tests to ensure quality criteria are met"),
            new Phase("install", "Install the package into the local repository for use as a dependency"),
            new Phase("deploy", "Copy the final package to the remote repository for sharing")
    );

    /**
     * The clean lifecycle phases.
     */
    public static final List<Phase> CLEAN_LIFECYCLE = List.of(
            new Phase("pre-clean", "Execute processes needed prior to the actual project cleaning"),
            new Phase("clean", "Remove all files generated by the previous build"),
            new Phase("post-clean", "Execute processes needed to finalize the project cleaning")
    );

    /**
     * Returns all phases that execute when the given phase is invoked.
     * In Maven, invoking a phase runs all preceding phases in the lifecycle.
     *
     * @param targetPhase the phase to invoke
     * @return the list of phases that will execute (in order), or an empty list
     *         if the phase is not found in the default lifecycle
     */
    public static List<Phase> phasesUpTo(String targetPhase) {
        for (int i = 0; i < DEFAULT_LIFECYCLE.size(); i++) {
            if (DEFAULT_LIFECYCLE.get(i).name().equals(targetPhase)) {
                return DEFAULT_LIFECYCLE.subList(0, i + 1);
            }
        }
        return List.of();
    }

    /**
     * Returns the phase description, or a "not found" message.
     *
     * @param phaseName the phase name
     * @return the description
     */
    public static String describePhase(String phaseName) {
        return DEFAULT_LIFECYCLE.stream()
                .filter(p -> p.name().equals(phaseName))
                .findFirst()
                .map(Phase::description)
                .orElse("Unknown phase: " + phaseName);
    }

    public static void main(String[] args) {
        System.out.println("=== Maven Default Lifecycle ===");
        System.out.println();
        for (Phase phase : DEFAULT_LIFECYCLE) {
            System.out.printf("  %-10s — %s%n", phase.name(), phase.description());
        }

        System.out.println();
        System.out.println("Running 'mvn test' executes:");
        phasesUpTo("test").forEach(p -> System.out.println("  → " + p.name()));
    }
}
